version: '3.7'
services:
  webdis:
    image: lnlscon/webdis:v0.1.10
    hostname: webdis
    build:
      context: "webdis/"
      dockerfile: "Dockerfile"
    ports:
      - '6380:6379'
      - '7379:7379'

  epics:
    image: lnlscon/http-epics:v1.5
    hostname: epics
    build:
      context: "epics-redis/"
      dockerfile: "Dockerfile"
      labels:
        - "br.com.lnls-sirius.description=EPICS HTTP Interface"
        - "br.com.lnls-sirius.department=CONS"
        - "br.com.lnls-sirius.maintener=Claudio Ferreira Carneiro"
    network_mode: host
#   ports:
#     - "5064:5064/tcp"
#     - "5064:5064/udp"
    volumes:
      - "./epics-redis/PV.txt:/opt/PV.txt"
    environment:
      - "SRV_HOST=10.128.255.5"
      - "SRV_PORT=6380"
      - "SRV_DB=0"

# conv:
#   image: lnlscon/epics-conv:v1.2
#   hostname: conv
#   build:
#     context: "conv-ioc/"
#     dockerfile: "Dockerfile"
#     labels:
#       - "br.com.lnls-sirius.description=Conversion IOC"
#       - "br.com.lnls-sirius.department=CONS"
#       - "br.com.lnls-sirius.maintener=Claudio Ferreira Carneiro"
#   ports:
#     - "5064:5064/tcp"
#     - "5064:5064/udp"
#   environment:
#     - "PORT=22105"
