version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  webdis:
    image: anapsix/webdis
    ports:
      - '7379:7379'
  web:
    image: httpd
    ports:
      - '8080:80'
    volumes:
      - './web-page:/usr/local/apache2/htdocs/epics'
      - './sirius-web-mon/build:/usr/local/apache2/htdocs/sirius-web-mon'
        
