version: '3.7'
services:
  redis:
    image: redis
    ports:
      - '6380:6379'
  webdis:
    image: anapsix/webdis
    environment:
      - "VERBOSITY=3"
      - "REDIS_HOST=10.128.255.5"
      - "REDIS_PORT=6380"
      - "DATABASE=0"
      - "HTTP_HOST=10.128.255.5"
      - "HTTP_PORT=7379"
      - "THREADS=5"
      - "POOL_SIZE=10"
      - "WEBSOCKETS=false"
    ports:
      - '7379:7379'
  epics:
    image: lnlscon/http-epics:v1.1
    build:
      context: "."
      dockerfile: "Dockerfile"
      labels:
        - "br.com.lnls-sirius.description=EPICS HTTP Interface"
        - "br.com.lnls-sirius.department=CONS"
        - "br.com.lnls-sirius.maintener=Claudio Ferreira Carneiro"
    ports:
      - "5064:5064/tcp"
      - "5064:5064/udp"
    environment:
      - "SRV_HOST=10.128.255.5"
      - "SRV_PORT=7379"
